export const monsters = [
  {
    id: "slime",
    name: "Slime",
    difficulty: "easy",
    image: "/assets/monsters/slime.webp",
  },
  {
    id: "goblin",
    name: "Goblin",
    difficulty: "medium",
    image: "/assets/monsters/goblin.webp",
  },
  {
    id: "dragon",
    name: "Red Dragon",
    difficulty: "hard",
    image: "/assets/monsters/dragon.webp",
  },
  {
    id: "bat",
    name: "Cave Bat",
    difficulty: "easy",
    image: "/assets/monsters/bat.webp",
  },
  {
    id: "rat",
    name: "Giant Rat",
    difficulty: "easy",
    image: "/assets/monsters/rat.webp",
  },
  {
    id: "zombie",
    name: "Zombie",
    difficulty: "medium",
    image: "/assets/monsters/zombie.webp",
  },
  {
    id: "skeleton",
    name: "Skeleton Warrior",
    difficulty: "medium",
    image: "/assets/monsters/skeleton.webp",
  },
  {
    id: "bee",
    name: "Killer Bee",
    difficulty: "easy",
    image: "/assets/monsters/bee.webp",
  },
  {
    id: "orc",
    name: "Orc",
    difficulty: "medium",
    image: "/assets/monsters/orc.webp",
  },
  {
    id: "ghost",
    name: "Restless Ghost",
    difficulty: "easy",
    image: "/assets/monsters/ghost.webp",
  },
  {
    id: "bandit",
    name: "Forest Bandit",
    difficulty: "medium",
    image: "/assets/monsters/bandit.webp",
  },
  {
    id: "mimic",
    name: "Mimic Chest",
    difficulty: "medium",
    image: "/assets/monsters/mimic.webp",
  },
  {
    id: "wolf",
    name: "Dire Wolf",
    difficulty: "medium",
    image: "/assets/monsters/wolf.webp",
  },
  {
    id: "snake",
    name: "Venom Snake",
    difficulty: "medium",
    image: "/assets/monsters/snake.webp",
  },
  {
    id: "imp",
    name: "Imp",
    difficulty: "medium",
    image: "/assets/monsters/imp.webp",
  },
  {
    id: "plant",
    name: "Carnivorous Plant",
    difficulty: "easy",
    image: "/assets/monsters/plant.webp",
  },
  {
    id: "skeleton-archer",
    name: "Skeleton Archer",
    difficulty: "medium",
    image: "/assets/monsters/skeleton-archer.webp",
  },
  {
    id: "crow",
    name: "Dark Crow",
    difficulty: "easy",
    image: "/assets/monsters/crow.webp",
  },
  {
    id: "kobold",
    name: "Kobold Miner",
    difficulty: "medium",
    image: "/assets/monsters/kobold.webp",
  },
  {
    id: "frog",
    name: "Poison Frog",
    difficulty: "easy",
    image: "/assets/monsters/frog.webp",
  },
  {
    id: "catbandit",
    name: "Cat Bandit",
    difficulty: "medium",
    image: "/assets/monsters/catbandit.webp",
  },
  {
    id: "bat-fire",
    name: "Fire Bat",
    difficulty: "medium",
    image: "/assets/monsters/bat-fire.webp",
  },
  {
    id: "skeleton-mage",
    name: "Skeleton Mage",
    difficulty: "medium",
    image: "/assets/monsters/skeleton-mage.webp",
  },
  {
    id: "lich",
    name: "Ancient Lich",
    difficulty: "hard",
    image: "/assets/monsters/lich.webp",
  },
  {
    id: "chimera",
    name: "Chimera Beast",
    difficulty: "hard",
    image: "/assets/monsters/chimera.webp",
  },
  {
    id: "black-slime",
    name: "Black Slime",
    difficulty: "medium",
    image: "/assets/monsters/black-slime.webp",
  },
];
