export const npcs = [
  {
    id: "healer_1",
    name: "Aira the Healer",
    trait: "kind",
    image: "/assets/npcs/aira.webp",
  },
  {
    id: "merchant_1",
    name: "Gregor the Merchant",
    trait: "greedy",
    image: "/assets/npcs/gregor.webp",
  },
  {
    id: "scout_1",
    name: "Lyn the Scout",
    trait: "cautious",
    image: "/assets/npcs/lyn.webp",
  },
  {
    id: "blacksmith_1",
    name: "Thorne the Blacksmith",
    trait: "strong",
    image: "/assets/npcs/thorne.webp",
  },
  {
    id: "innkeeper_1",
    name: "Mira the Innkeeper",
    trait: "welcoming",
    image: "/assets/npcs/mira.webp",
  },
  {
    id: "bard_1",
    name: "Elric the Bard",
    trait: "cheerful",
    image: "/assets/npcs/elric.webp",
  },
  {
    id: "alchemist_1",
    name: "Selene the Alchemist",
    trait: "curious",
    image: "/assets/npcs/selene.webp",
  },
  {
    id: "guard_1",
    name: "Doran the Guard",
    trait: "loyal",
    image: "/assets/npcs/doran.webp",
  },
  {
    id: "farmer_1",
    name: "Old Man Theo",
    trait: "wise",
    image: "/assets/npcs/theo.webp",
  },
  {
    id: "child_1",
    name: "Pip the Orphan",
    trait: "playful",
    image: "/assets/npcs/pip.webp",
  },
  {
    id: "witch_1",
    name: "Grenda the Witch",
    trait: "mysterious",
    image: "/assets/npcs/grenda.webp",
  },
  {
    id: "noble_1",
    name: "Lady Evelyn",
    trait: "arrogant",
    image: "/assets/npcs/evelyn.webp",
  },
  {
    id: "hunter_1",
    name: "Rurik the Hunter",
    trait: "brave",
    image: "/assets/npcs/rurik.webp",
  },
  {
    id: "sage_1",
    name: "Elandor the Sage",
    trait: "intelligent",
    image: "/assets/npcs/elandor.webp",
  },
  {
    id: "cook",
    name: "Bela the Cook",
    trait: "hospitable",
    image: "/assets/npcs/bela.webp",
  },
  {
    id: "stablemaster",
    name: "Kreg the Stablemaster",
    trait: "gentle",
    image: "/assets/npcs/kreg.webp",
  },
  {
    id: "fisherman",
    name: "Noll the Fisherman",
    trait: "calm",
    image: "/assets/npcs/noll.webp",
  },
  {
    id: "priestess",
    name: "Anya the Priestess",
    trait: "faithful",
    image: "/assets/npcs/anya.webp",
  },
  {
    id: "miner",
    name: "Burk the Miner",
    trait: "hardworking",
    image: "/assets/npcs/burk.webp",
  },
  {
    id: "tailor",
    name: "Lysa the Tailor",
    trait: "patient",
    image: "/assets/npcs/lysa.webp",
  },
  {
    id: "shepherd",
    name: "Toma the Shepherd",
    trait: "peaceful",
    image: "/assets/npcs/toma.webp",
  },
  {
    id: "traveler",
    name: "Finn the Traveler",
    trait: "curious",
    image: "/assets/npcs/finn.webp",
  },
  {
    id: "sailor",
    name: "Marro the Sailor",
    trait: "adventurous",
    image: "/assets/npcs/marro.webp",
  },
  {
    id: "gravekeeper",
    name: "Edrin the Gravekeeper",
    trait: "silent",
    image: "/assets/npcs/edrin.webp",
  },
  {
    id: "herbalist",
    name: "Faye the Herbalist",
    trait: "gentle",
    image: "/assets/npcs/faye.webp",
  },
  {
    id: "tavern_bouncer",
    name: "Gorn the Bouncer",
    trait: "gruff",
    image: "/assets/npcs/gorn.webp",
  },
  {
    id: "maid_1",
    name: "Nina the Maid",
    trait: "polite",
    image: "/assets/npcs/nina.webp",
  },
  {
    id: "messenger",
    name: "Zeke the Messenger",
    trait: "swift",
    image: "/assets/npcs/zeke.webp",
  },
  {
    id: "carpenter_1",
    name: "Walt the Carpenter",
    trait: "reliable",
    image: "/assets/npcs/walt.webp",
  },
  {
    id: "fortune_teller_1",
    name: "Mysta the Fortune Teller",
    trait: "enigmatic",
    image: "/assets/npcs/mysta.webp",
  },
  {
    id: "apprentice_1",
    name: "Juno the Apprentice",
    trait: "eager",
    image: "/assets/npcs/juno.webp",
  },
  {
    id: "scribe_1",
    name: "Elias the Scribe",
    trait: "meticulous",
    image: "/assets/npcs/elias.webp",
  },
  {
    id: "beggar",
    name: "Rolo the Beggar",
    trait: "hopeful",
    image: "/assets/npcs/rolo.webp",
  },
  {
    id: "retired_knight",
    name: "Sir Harlon",
    trait: "honorable",
    image: "/assets/npcs/harlon.webp",
  },
  {
    id: "healer_2",
    name: "Mina the Lightbringer",
    trait: "devoted",
    image: "/assets/npcs/mina.webp",
  },
  {
    id: "merchant_2",
    name: "Tarek the Trader",
    trait: "opportunistic",
    image: "/assets/npcs/tarek.webp",
  },
  {
    id: "scout_2",
    name: "Jaren the Pathseeker",
    trait: "sharp-eyed",
    image: "/assets/npcs/jaren.webp",
  },
  {
    id: "blacksmith_2",
    name: "Runa the Smith",
    trait: "focused",
    image: "/assets/npcs/runa.webp",
  },
  {
    id: "innkeeper_2",
    name: "Borin the Brewmaster",
    trait: "jovial",
    image: "/assets/npcs/borin.webp",
  },
  {
    id: "bard_2",
    name: "Syl the Songweaver",
    trait: "dramatic",
    image: "/assets/npcs/syl.webp",
  },
  {
    id: "alchemist_2",
    name: "Dray the Mixer",
    trait: "reckless",
    image: "/assets/npcs/dray.webp",
  },
  {
    id: "guard_2",
    name: "Vel the Watcher",
    trait: "protective",
    image: "/assets/npcs/vel.webp",
  },
  {
    id: "farmer_2",
    name: "Ludo the Tiller",
    trait: "simple",
    image: "/assets/npcs/ludo.webp",
  },
  {
    id: "child_2",
    name: "Kiki the Curious",
    trait: "imaginative",
    image: "/assets/npcs/kiki.webp",
  },
  {
    id: "witch_2",
    name: "Morga the Crone",
    trait: "cryptic",
    image: "/assets/npcs/morga.webp",
  },
  {
    id: "noble_2",
    name: "Lord Ferwin",
    trait: "demanding",
    image: "/assets/npcs/ferwin.webp",
  },
  {
    id: "hunter_2",
    name: "Velma the Tracker",
    trait: "focused",
    image: "/assets/npcs/velma.webp",
  },
  {
    id: "sage_2",
    name: "Iroden the Seer",
    trait: "reserved",
    image: "/assets/npcs/iroden.webp",
  },
  {
    id: "maid_2",
    name: "Sera the Silent",
    trait: "observant",
    image: "/assets/npcs/sera.webp",
  },
  {
    id: "carpenter_2",
    name: "Dego the Fixer",
    trait: "stubborn",
    image: "/assets/npcs/dego.webp",
  },
  {
    id: "scribe_2",
    name: "Tilda the Copyist",
    trait: "forgetful",
    image: "/assets/npcs/tilda.webp",
  },
  {
    id: "fortune_teller_2",
    name: "Zara the Visionary",
    trait: "spiritual",
    image: "/assets/npcs/zara.webp",
  },
  {
    id: "apprentice_2",
    name: "Orin the Learner",
    trait: "clumsy",
    image: "/assets/npcs/orin.webp",
  },
  {
    id: "guard_3",
    name: "Rokk the Wall",
    trait: "silent",
    image: "/assets/npcs/rokk.webp",
  },
];
